---

- name: Install Nrpe and Plugins (Ubuntu)
  apt: pkg={{ item.package }}
       state=latest
       update_cache=yes
       install_recommends=no
  with_items: "{{ nrpe_agent_Debian }}"
  tags:
   - nrpe_agent_install

- name: Install check_mem (Ubuntu)
  template: src=check_mem
            mode=0755
            owner=root
            group=root
            dest="{{ nrpe_agent_plugins_x86_64 }}"

- name: Copy Nrpe Configuration (Ubuntu)
  template: src=nrpe.cfg.j2
            dest={{ nrpe_agent_config }}
            owner=root
            group=root
            mode=0644
            backup=yes
  tags:
   - nrpe_agent_config

- name: Fix nagios-nrpe-server init script (Ubuntu)
  template: src=nagios-nrpe-server.j2
            dest="/etc/init.d/nagios-nrpe-server"

- name: Start nagios-nrpe-server
  shell: systemctl daemon-reload
  notify:
    - restart nagios-nrpe-server